# -*- coding: utf-8 -*-
"""Auswahl der Shop-Avatare.

(Datei-ID, Kartenname, cx, cy): cx/cy = Mittelpunkt des 64x64-Ausschnitts im nativen Kartenraster (152x99)."""
PICKS = [
    ("Alleria",        "Alleria, the Queen of Spiders",          78, 45),
    ("BalladHarpy",    "Ballad Harpyformer",                     70, 52),
    ("Blackstache",    "Blackstache, Scourge of the Pixel Seas", 76, 52),
    ("Mellvy",         "Bonded Companion Mellvy",                76, 45),
    ("Orphy",          "Bonded Companion Orphy",                 52, 50),
    ("Censpartan",     "Censpartan War Counselor",               84, 52),
    ("Crum",           "Crum, the Class Pet",                    76, 50),
    ("Molinda",        "Cute Angel Molinda",                     76, 50),
    ("Mini",           "Cute Annoyance Mini",                    76, 50),
    ("CuteBird",       "Cute Bird",                              76, 45),
    ("CuteHydra",      "Cute Hydra",                             76, 45),
    ("DemonsGate",     "Demon's Gate",                           76, 40),
    ("Shishi",         "Destructive Puppet Shishi",              76, 50),
    ("ForestWarden",   "Disgruntled Forest Warden",              76, 55),
    ("JaguarWarrior",  "Ferocious Jaguar Warrior",               76, 55),
    ("ExplodingSkull", "Giant Exploding Skull",                  76, 45),
    ("Grisgar",        "Grisgar, Emissary of the Demon Lord",    76, 60),
    ("Harpthenean",    "Harpthenean War Counselor",              76, 50),
    ("Hatusbal",       "Hatusbal, the Leader of Tusca",          76, 50),
    ("Hipdall",        "Hipdall, Protector of Coolness",         76, 52),
    ("LawnGnome",      "Inconspicuous Lawn Gnome",               76, 55),
    ("Koperniko",      "Koperniko, the Stargazer",               76, 55),
    ("Minocrete",      "Minocrete War Counselor",                90, 55),
    ("Phatnir",        "Phatnir, Prototype of Coolness",         76, 50),
    ("TimidTanuki",    "Rebelliokai Timid Tanuki",               76, 50),
    ("RoyalCorgi",     "Royal Corgi",                            76, 55),
    ("SandyBlob",      "Sandy Blob",                             76, 50),
    ("ShantyHarpy",    "Shanty Harpyformer",                     76, 50),
    ("SlipperyPolar",  "Slippery Polar",                         60, 55),
    ("BarbarianSword", "Spirit of the Barbarian Sword",          76, 50),
    ("SwiftEagle",     "Swift Eagle Warrior",                    76, 50),
    ("TimeBomblebee",  "Time Bomblebee",                         76, 50),
    ("Willy",          "Willy, the Valiant Leprechaun",          76, 55),
    ("Wowkyrie",       "Wowkyrie, Bringer of Coolness",          70, 50),
    ("Baihu",          "Cardinal Beast Baihu",                   76, 50),
    ("RedDragoneer",   "Red Dragoneer",                          76, 50),
    ("Rubin",          "Rubin, the Dragoneer Champion",          76, 50),
    ("Strongman",      "Fun-Fun Circus Strongman",               76, 55),
    ("CircusDirector", "Fun-Fun Circus Director",                76, 55),
    ("CircusClown",    "Fun-Fun Circus Clown",                   76, 50),
    ("Asriel",         "Asriel, the Sapling Sacrificer",         76, 50),
    ("Freshya",        "Freshya, Beauty of Coolness",            76, 50),
    ("DonQuisto",      "Don Quisto, the Gold Seeker",            54, 55),
]
