# -*- coding: utf-8 -*-
"""Auswahl der Shop-Avatare.

(Datei-ID, Kartenname, cx, cy): cx/cy = Mittelpunkt des Ausschnitts im nativen Kartenraster (152x99); optional 5. Wert = Kantenlänge
(Standard 64, kleiner = stärker hineingezoomt)."""
PICKS = [
    ("BalladHarpy",    "Ballad Harpyformer",                     70, 52),
    ("Blackstache",    "Blackstache, Scourge of the Pixel Seas", 76, 52),
    ("Mellvy",         "Bonded Companion Mellvy",                76, 45, 44),
    ("Orphy",          "Bonded Companion Orphy",                 61, 50),
    ("Censpartan",     "Censpartan War Counselor",               84, 52),
    ("Crum",           "Crum, the Class Pet",                    76, 50, 44),
    ("Molinda",        "Cute Angel Molinda",                     76, 50),
    ("Mini",           "Cute Annoyance Mini",                    76, 50),
    ("CuteBird",       "Cute Bird",                              76, 45),
    ("CuteHydra",      "Cute Hydra",                             76, 45),
    ("DemonsGate",     "Demon's Gate",                           76, 40),
    ("Shishi",         "Destructive Puppet Shishi",              76, 50),
    ("JaguarWarrior",  "Ferocious Jaguar Warrior",               76, 55),
    ("ExplodingSkull", "Giant Exploding Skull",                  76, 45),
    ("Grisgar",        "Grisgar, Emissary of the Demon Lord",    76, 60),
    ("Harpthenean",    "Harpthenean War Counselor",              76, 50),
    ("Hatusbal",       "Hatusbal, the Leader of Tusca",          76, 50),
    ("Hipdall",        "Hipdall, Protector of Coolness",         76, 52),
    ("LawnGnome",      "Inconspicuous Lawn Gnome",               76, 55, 36),
    ("Koperniko",      "Koperniko, the Stargazer",               76, 55),
    ("Minocrete",      "Minocrete War Counselor",                90, 55),
    ("TimidTanuki",    "Rebelliokai Timid Tanuki",               76, 50),
    ("RoyalCorgi",     "Royal Corgi",                            76, 55, 36),
    ("SandyBlob",      "Sandy Blob",                             76, 50),
    ("ShantyHarpy",    "Shanty Harpyformer",                     76, 50),
    ("SwiftEagle",     "Swift Eagle Warrior",                    76, 50),
    ("TimeBomblebee",  "Time Bomblebee",                         76, 50),
    ("Willy",          "Willy, the Valiant Leprechaun",          76, 55, 40),
    ("Wowkyrie",       "Wowkyrie, Bringer of Coolness",          70, 50),
    ("RedDragoneer",   "Red Dragoneer",                          76, 50),
    ("Rubin",          "Rubin, the Dragoneer Champion",          76, 50),
    ("CircusDirector", "Fun-Fun Circus Director",                76, 55),
    ("CircusClown",    "Fun-Fun Circus Clown",                   76, 50),
    ("Asriel",         "Asriel, the Sapling Sacrificer",         76, 50),
    ("Freshya",        "Freshya, Beauty of Coolness",            76, 50),
    ("DonQuisto",      "Don Quisto, the Gold Seeker",            63, 55),
    ("CactusCreature", "Cactus Creature", 77, 50, 64),
    ("CybugBee", "Cybug BEE", 77, 50, 100),
    ("Stegon", "Gigantisaur Stegon", 50, 55, 100),
    ("Greatmaw", "Greatmaw Siren", 77, 50, 70),
    ("BearRider", "Mischief Militia - Bear Rider", 77, 57, 56),
    ("GreenDragoneer", "Green Dragoneer", 72, 57, 60),
    ("Bomblebee", "Carpet Bomblebee", 77, 57, 70),
    ("PrincessMary", "Cute Princess Mary", 77, 57, 70),
    ("CybugScarab", "Cybug SCARAB", 77, 57, 70),
    ("CykyranCounselor", "Cykyran War Counselor", 63, 57, 56),
    ("ElvenRider", "Elven Rider", 77, 57, 60),
    ("Garius", "Garius, the Great Reformer", 77, 53, 64),
    ("Gobbo", "Gobbo, Chief of Goblin", 77, 57, 52),
    ("GoldenSkull", "Golden Exploding Skull", 77, 47, 50),
    ("Gon", "Gon, the Frostbringer", 77, 57, 56),
    ("GorinthianCounselor", "Gorinthian War Counselor", 77, 53, 50),
    ("GraveWorm", "Grave Worm", 77, 53, 70),
    ("Teocuilatl", "Guardian of Teocuilatl", 77, 57, 56),
    ("HammerSkeleton", "Hammer Skeleton", 77, 57, 56),
    ("SkeletonHealer", "Skeleton Healer", 77, 63, 56),
    ("Hel", "Hel, the Bound Specter", 77, 57, 56),
    ("IcySlime", "Icy Slime", 77, 53, 50),
    ("Daiyo", "Idej Lord Daiyo", 77, 47, 56),
    ("Kassaran", "Kassaran, Seer of Everything", 77, 67, 56),
    ("GreatmawShark", "Greatmaw Shark", 77, 53, 100),
    ("CosmicInvader", "Invader from the Cosmic Depths", 77, 53, 100),
    ("ElvenArcher", "Elven Archer", 77, 57, 48),
    ("CutePhoenix", "Cute Phoenix", 77, 53, 80),
    ("GuardianBeastLong", "Guardian Beast Long", 77, 60, 80),
    ("NimbleMonkee", "Nimble Monkee", 73, 77, 44),
    ("BakusGargoyle", "Rebelliokai Backup Bakus", 77, 40, 48),
    ("Damus", "Damus, the Prophet of Apocalypse", 73, 50, 56),
    ("ElvenDruid", "Elven Druid", 77, 57, 56),
    ("GhoulGuard", "Ghoul Guard", 53, 50, 48),
    ("Raptoren", "Gigantisaur Raptoren", 77, 47, 80),
    ("Brachion", "Gigantisaur Brachion", 98, 53, 100),
    ("Karian", "Grand Inquisitor Karian", 77, 60, 60),
    ("Remora", "Greatmaw Remora", 77, 53, 100),
    ("Heragas", "Heragas, the Monster Slayer", 77, 57, 70),
    ("InvaderToken", "Invader Token", 77, 67, 100),
    ("Junshi", "Junshi, the Tactical Genius", 78, 54, 50),
    ("Kit", "Kit, the Shark Researcher", 60, 57, 56),
    ("CuteSpider", "Cute Spider", 77, 47, 56),
    ("MonsterNest", "Monster Nest", 77, 53, 64),
    ("Guldefaber", "Güldefaber, the King of Dwarfs", 77, 61, 64),
    ("Tobi", "Tobi, the Average Student", 77, 64, 50),
    ("CheekyMonkee", "Cheeky Monkee", 60, 55, 44),
    ("LunaKiai", "Luna Kiai", 77, 60, 80),
    ("LunaPele", "Luna Pele, the Flame Dancer", 77, 53, 56),
    ("Luna", "Luna, the Flame Fairy", 77, 63, 70),
    ("MetalHarpyformer", "Metal Harpyformer", 77, 57, 56),
    ("Mirjam", "Mirjam, the Fallen Cute Angel", 77, 53, 50),
    ("MummyToken", "Mummy Token", 77, 73, 60),
    ("NobleMummyGuards", "Noble Mummy Guards", 77, 67, 90),
    ("Nomu", "Nomu, Wanderer of Worlds", 77, 54, 50),
    ("Omikron", "Omikron, the Faceless Illusionist", 77, 57, 70),
    ("Nieht", "Nieht, the Blitz Blade", 77, 63, 56),
    ("LovingPuppetPavi", "Loving Puppet Pavi", 77, 47, 56),
    ("PollutionPiranha", "Pollution Piranha", 77, 63, 64),
    ("CamouflagedKappa", "Rebelliokai Camouflaged Kappa", 77, 67, 56),
    ("CourtlyKirin", "Rebelliokai Courtly Kirin", 77, 53, 64),
    ("Rafflesia", "Rafflesia, the Poison Princess", 77, 53, 56),
    ("KindKitsune", "Rebelliokai Kind Kitsune", 77, 53, 56),
    ("TerrorTengu", "Rebelliokai Terror Tengu", 77, 57, 60),
    ("RhaBi", "Rha'Bi, the Living Skeleton", 77, 60, 60),
    ("Saya", "Saya, the Plant Princess", 77, 57, 60),
    ("SkeletonBard", "Skeleton Bard", 77, 73, 60),
    ("SkeletonMage", "Skeleton Mage", 77, 53, 56),
    ("ShardBa", "Soul Shard Ba", 77, 53, 64),
    ("ShardSah", "Soul Shard Sah", 77, 67, 70),
    ("ShardShut", "Soul Shard Shut", 77, 46, 56),
    ("DwarfDiver", "Steam Dwarf Diver", 77, 57, 56),
    ("DwarfEngineer", "Steam Dwarf Engineer", 77, 63, 64),
    ("SuspiciousMonster", "Suspicious Monster", 77, 57, 56),
    ("SlipperySnowman", "Slippery Snowman", 90, 56, 48),
]
