# -*- coding: utf-8 -*-
"""
Erzeugt ein RPG-Maker-2003-Charset (24×32 px pro Frame, 3 Frames × 4 Richtungen)
für „Cool Rescuer Monia“. Monia schwebt mit Jetpack: statt Laufschritten gibt es
Schwebe-Bob, Flammenflackern und eine pulsierende Haarspange.

Aufruf:  python3 scripts/charsets/monia_charset.py [--preview DIR]
Ausgabe: data/hero-charsets/cool-rescuer-monia.png        (72×128, transparent)
         data/hero-charsets/cool-rescuer-monia.sheet.png  (288×256, 2k3-Grün, Slot 0)
"""
import os, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT_DIR = os.path.join(ROOT, 'data', 'hero-charsets')
FW, FH = 24, 32
GREEN = (32, 156, 0, 255)

# ---------------------------------------------------------------- Palette
PAL = {
    '.': None,
    # Haare (dunkles Marineblau)
    'h': (0, 12, 34),      # Outline
    'H': (0, 36, 78),      # dunkel
    'n': (6, 62, 124),     # Grundton
    'N': (22, 96, 176),    # hell
    'l': (70, 150, 225),   # Glanzsträhne
    # Haarspange / Funkeln
    '*': (246, 255, 255),
    'c': (120, 236, 255),
    # Haut
    'o': (72, 36, 22),     # Outline
    'd': (198, 138, 104),  # Schatten
    's': (247, 196, 160),  # Grundton
    'S': (253, 228, 208),  # hell
    # Augen
    'k': (0, 0, 0),
    'e': (20, 10, 170),    # Iris dunkel
    'E': (130, 150, 255),  # Iris hell
    # Jacke / Kleidung
    'A': (0, 0, 0),        # Outline
    'j': (40, 40, 46),     # dunkel
    'J': (66, 66, 74),     # Grundton
    'g': (96, 96, 106),    # hell (Ärmel)
    'G': (134, 134, 146),  # Revers
    'w': (246, 246, 246),  # Hemd
    'W': (204, 204, 214),  # Hemd Schatten
    # Hose / Stiefel
    'p': (30, 30, 34),
    'P': (54, 54, 60),
    'b': (22, 22, 24),
    'B': (50, 50, 54),
    # Düsen (Metall)
    'm': (62, 66, 72),
    'M': (108, 114, 122),
    'i': (166, 174, 182),
    # Flammen
    'r': (210, 44, 40),
    'O': (246, 140, 30),
    'y': (255, 216, 40),
    'Y': (255, 247, 184),
}

def grid(rows):
    """Text-Map → Liste von Zeilen; prüft Breite 24 und Höhe 32."""
    rows = [r for r in rows.strip('\n').split('\n')]
    assert len(rows) == FH, f'{len(rows)} Zeilen statt {FH}'
    for i, r in enumerate(rows):
        assert len(r) == FW, f'Zeile {i} hat {len(r)} Zeichen: {r!r}'
    return [list(r) for r in rows]

# ---------------------------------------------------------------- Grundposen (mittlerer Frame)
# Spalten:   012345678901234567890123
DOWN = grid("""
........................
........................
........................
........................
................h.......
...............hNh......
.........hhhhhhHNh......
........hHnNNnnHNh......
.......hHnNlNnnnNlh.....
......hHnNlNnnnnNlh.....
.....hHnnNNNnnnnNnh.....
.....hHnnnNNnnnnnnh.....
.....hHnnNnnnnhssnh.....
.....hHnnhsnnhsssnh.....
.....hHnskknhkkssnh.....
.....hHnsEehseEsdnh.....
......hHssSSSSssdo......
.......hodsSSsdo........
.....AjJwAdssdAwJjA.....
.....AjJJJGwWGJJJjA.....
.....AgjAJGwWGJAjgA.....
.....AgjAJGwWGJAjgA.....
.....AgjAJGwWGJAjgA.....
.....AgjAJGwWGJAjgA.....
.....osdAJJwWJJAdso.....
......ooAjjjjjjAoo......
........APpAApPA........
........APpAApPA........
........ABbAAbBA........
........AAAAAAAA........
........................
........................
""")

UP = grid("""
........................
........................
........................
........................
.......h................
......hNh...............
......hNHhhhhhh.........
......hnHnNNnnHh........
......hlnNllNnnNHh......
.....hlNnNlNNnNnnHh.....
.....hHnNNlNNnNnnHh.....
.....hHnnNNNNnnNnHh.....
.....hHnnnNNnnnnnHh.....
.....hHHnnnnnnnnHHh.....
.....hHHHnnnnnnHHHh.....
......hHHHnnnnHHHh......
......hHHHHHHHHHHh......
......hHhodssdohHh......
.....AjJJAdssdAJJjA.....
.....AjJAiMMMMiAJjA.....
.....AgjAiMMMMiAjgA.....
.....AgjAMmmmmMAjgA.....
.....AgjAiMMMMiAjgA.....
.....AgjAMMMMMMAjgA.....
.....osdAmmmmmmAdso.....
......ooAjjjjjjAoo......
........APpAApPA........
........APpAApPA........
........ABbAAbBA........
........AAAAAAAA........
........................
........................
""")

RIGHT = grid("""
........................
........................
........................
........................
.........h..............
........hNh.............
........hNHhhhhh........
.......hnnNNNnnnHh......
......hHnNllNNnnnnHh....
......hHnNlNNnnnnnnh....
.....hHHnNNnnnnnnnh.....
.....hHHnnNnnnnnnnNh....
.....hHHnnnnnnnhsnnh....
.....hHHnnhshskkso......
.....hHHnhssssEeso......
.....hHHhssSSsssdo......
......hHhodsSSssdo......
.......hHhoodsSdo.......
.......AjJJodsowA.......
.......AjJJJJJGwA.......
.......AjJAgjJwA........
.......AjJAgjJwA........
.......AjJAgjJwA........
.......AjJAgjJwA........
.......AjJosdJwA........
.......AjjoojjjA........
.........APppPA.........
.........APppPA.........
.........ABbbBBA........
.........AAAAAAA........
........................
........................
""")

# ---------------------------------------------------------------- Düsen & Flammen
# Düse (4 breit, Zeilen 19–22), links; rechts wird gespiegelt
THRUSTER = ['AAAm', 'AiMm', 'AiMm', 'AmmA']
# Drei Flammen-Varianten (Flackern), je 8 Zeilen ab Zeile 23, 4 breit
FLAMES = [
    ['OYYO', 'ryYO', 'rOyr', '.ryr', '.rOr', '.rr.', '..r.', '....'],   # kurz
    ['OYYO', 'ryYO', 'rOyr', '.ryr', '.rOr', '.rr.', '..r.', '..r.'],   # mittel
    ['OYYO', 'rYyO', 'ryOr', 'rOyr', '.ryr', '.rOr', '.rr.', '..r.'],   # lang/breit
]
# Haarspange: Funkel-Stufen (relativ zum Zentrum)
STARS = [
    [(0, 0, '*')],
    [(0, 0, '*'), (-1, 0, 'c'), (1, 0, 'c'), (0, -1, 'c'), (0, 1, 'c')],
    [(0, 0, '*'), (-1, 0, '*'), (1, 0, '*'), (0, -1, '*'), (0, 1, '*'),
     (-2, 0, 'c'), (2, 0, 'c'), (0, -2, 'c'), (0, 2, 'c')],
]

def blit(g, rows, x0, y0, mirror=False):
    for dy, row in enumerate(rows):
        if mirror:
            row = row[::-1]
        for dx, ch in enumerate(row):
            if ch != '.' and 0 <= y0 + dy < FH and 0 <= x0 + dx < FW:
                g[y0 + dy][x0 + dx] = ch

def shift(g, dy):
    out = [['.'] * FW for _ in range(FH)]
    for y in range(FH):
        ny = y + dy
        if 0 <= ny < FH:
            out[ny] = list(g[y])
    return out

def mirror(g):
    return [row[::-1] for row in g]

def copy(g):
    return [list(r) for r in g]

def star(g, cx, cy, level):
    for dx, dy, ch in STARS[level]:
        x, y = cx + dx, cy + dy
        if 0 <= x < FW and 0 <= y < FH:
            g[y][x] = ch

def build_frame(direction, f):
    """direction ∈ up,right,down,left; f ∈ 0,1,2 → fertiges 24×32-Raster."""
    bob = (-1, 0, 1)[f]          # Schwebe-Bob: hoch, Mitte, tief
    flame = FLAMES[f]
    if direction == 'down':
        g = copy(DOWN)
        blit(g, THRUSTER, 1, 19);  blit(g, THRUSTER, 19, 19, mirror=True)
        g = shift(g, bob)
        star(g, 18, 12 + bob, f)
        blit(g, flame, 1, 23 + bob); blit(g, flame, 19, 23 + bob, mirror=True)
    elif direction == 'up':
        g = copy(UP)
        blit(g, THRUSTER, 1, 19);  blit(g, THRUSTER, 19, 19, mirror=True)
        g = shift(g, bob)
        star(g, 5, 12 + bob, f)
        blit(g, flame, 1, 23 + bob); blit(g, flame, 19, 23 + bob, mirror=True)
    elif direction == 'right':
        g = copy(RIGHT)
        blit(g, THRUSTER, 5, 19)
        g = shift(g, bob)
        blit(g, flame, 5, 23 + bob)
    elif direction == 'left':
        g = mirror(RIGHT)
        # linke Seite: Pony kürzer, Stirn freier
        g[12] = list('....hnssshnnnnnnHHh.....')
        g[13] = list('......oskksshnnnHHh.....')
        blit(g, THRUSTER, 15, 19, mirror=True)
        g = shift(g, bob)
        star(g, 11, 11 + bob, f)
        blit(g, flame, 15, 23 + bob, mirror=True)
    return g

def render(g):
    im = Image.new('RGBA', (FW, FH), (0, 0, 0, 0))
    px = im.load()
    for y in range(FH):
        for x in range(FW):
            c = PAL[g[y][x]]
            if c is not None:
                px[x, y] = c + (255,)
    return im

ORDER = ['up', 'right', 'down', 'left']   # Zeilenreihenfolge im 2k3-Charset

def build_charset():
    cs = Image.new('RGBA', (FW * 3, FH * 4), (0, 0, 0, 0))
    for r, d in enumerate(ORDER):
        for f in range(3):
            cs.paste(render(build_frame(d, f)), (f * FW, r * FH))
    return cs

def main():
    preview_dir = None
    if '--preview' in sys.argv:
        preview_dir = sys.argv[sys.argv.index('--preview') + 1]
    os.makedirs(OUT_DIR, exist_ok=True)
    cs = build_charset()
    cs.save(os.path.join(OUT_DIR, 'cool-rescuer-monia.png'))
    sheet = Image.new('RGBA', (288, 256), GREEN)
    sheet.paste(cs, (0, 0), cs)
    sheet.save(os.path.join(OUT_DIR, 'cool-rescuer-monia.sheet.png'))
    if preview_dir:
        os.makedirs(preview_dir, exist_ok=True)
        S = 6
        big = Image.new('RGBA', (FW * 3 * S, FH * 4 * S), GREEN)
        up = cs.resize(big.size, Image.NEAREST)
        big.paste(up, (0, 0), up)
        big.save(os.path.join(preview_dir, 'monia_charset_x6.png'))
        # GIF: alle 4 Richtungen nebeneinander, Frames 0-1-2-1
        frames = []
        for f in (0, 1, 2, 1):
            fr = Image.new('RGBA', (FW * 4 * S + 5 * S, FH * S), GREEN)
            for i, d in enumerate(ORDER):
                im = render(build_frame(d, f)).resize((FW * S, FH * S), Image.NEAREST)
                fr.paste(im, (S + i * (FW * S + S), 0), im)
            frames.append(fr.convert('P', palette=Image.ADAPTIVE))
        frames[0].save(os.path.join(preview_dir, 'monia_anim.gif'), save_all=True,
                       append_images=frames[1:], duration=180, loop=0, disposal=2)
    print('ok', cs.size)

if __name__ == '__main__':
    main()
