# -*- coding: utf-8 -*-
"""
Vier-Richtungen-Sheet für „Cool Rescuer Monia“ im Stil der Hero-Animationen.

Zeile „down“ ist das unveränderte Original (data/hero-animations/cool-rescuer-monia.png,
32 Frames à 36×37). Die anderen drei Richtungen werden daraus abgeleitet:

  up    – Original horizontal gespiegelt, darüber ein handgezeichnetes Overlay
          (Hinterkopf, Jackenrücken, Jetpack). Tolle, Stern, Düsen, Flammen und
          Beinpendeln kommen so Frame für Frame aus dem Original.
  right – handgezeichnete Ebenen (Kopf, Torso, Arm, Beine, Düse); Flamme pro Frame
          aus dem Original kopiert; Schwebe-Bob und Beinpendeln wie im Original.
  left  – gespiegelte Ebenen von „right“ mit erhobenem Arm (wie im Original die
          linke Faust) und dem pulsierenden Stern an der Haarspange.

Aufruf:  python3 scripts/charsets/monia_directions.py [--preview DIR]
Ausgabe: data/hero-charsets/cool-rescuer-monia.png   (1152×148: up, right, down, left)
"""
import os, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, 'data', 'hero-animations', 'cool-rescuer-monia.png')
OUT_DIR = os.path.join(ROOT, 'data', 'hero-charsets')
FW, FH, NF = 36, 37, 32

# ------------------------------------------------------------ Palette des Originals
PAL = {
    'A': (202, 44, 41),    'B': (0, 2, 0),        'C': (244, 123, 34),   'D': (246, 231, 14),
    'E': (0, 26, 51),      'F': (247, 245, 184),  'G': (14, 16, 12),     'H': (0, 46, 90),
    'I': (64, 65, 63),     'J': (0, 54, 103),     'K': (77, 79, 76),     'L': (19, 20, 18),
    'M': (1, 68, 131),     'N': (8, 61, 118),     'O': (49, 24, 0),      'P': (254, 255, 252),
    'Q': (56, 57, 55),     'R': (35, 36, 34),     'S': (31, 32, 30),     'T': (29, 31, 28),
    'U': (255, 255, 255),  'V': (0, 37, 70),      'W': (247, 188, 151),  'X': (180, 246, 255),
    'Y': (92, 94, 91),     'Z': (252, 231, 214),  'a': (207, 209, 206),  'b': (25, 27, 24),
    'c': (255, 165, 165),  'd': (255, 151, 151),  'e': (248, 188, 119),  'f': (245, 206, 136),
    'g': (65, 55, 4),      'h': (47, 49, 46),     'i': (242, 255, 255),  'j': (16, 0, 197),
    'k': (0, 251, 252),    'l': (0, 0, 130),      'm': (126, 146, 255),  'n': (30, 57, 255),
    'o': (28, 28, 28),     'p': (0, 0, 0),
}
SYM = {v: k for k, v in PAL.items()}
FLAME = {PAL[c] for c in 'ACDF'}
STAR_COLORS = {PAL['X'], PAL['U']}

# Schwebe-Bob je Frame (aus dem Original gemessen, 16er-Zyklus, zweimal)
DY = [0, 0, 0, -1, -1, -1, -2, -2, -2, -2, -2, -1, -1, -1, 0, 0] * 2
# Beinpendeln: ihr rechtes Bein (Betrachter links) in Frames 2–10, ihr linkes in 11–14
RIGHT_LEG_KICK = {f for f in range(NF) if 2 <= f % 16 <= 10}
LEFT_LEG_KICK = {f for f in range(NF) if 11 <= f % 16 <= 14}
STAR_CENTER = (23, 13)     # Sternmitte im Original (Frame-0-Koordinaten)

def layer(text):
    rows = text.strip('\n').split('\n')
    out = [['.'] * FW for _ in range(FH)]
    for y, r in enumerate(rows):
        assert len(r) == FW, f'Zeile {y} hat {len(r)} Zeichen: {r!r}'
        out[y] = list(r)
    assert len(rows) <= FH
    return out

def new_grid():
    return [['.'] * FW for _ in range(FH)]

def blit(dst, src, dx=0, dy=0, skip=None):
    for y in range(FH):
        for x in range(FW):
            ch = src[y][x]
            if ch == '.':
                continue
            tx, ty = x + dx, y + dy
            if 0 <= tx < FW and 0 <= ty < FH:
                if skip and skip(tx, ty):
                    continue
                dst[ty][tx] = ch

def mirror(g):
    return [row[::-1] for row in g]

def grid_from_image(img):
    px = img.load()
    g = new_grid()
    for y in range(FH):
        for x in range(FW):
            c = px[x, y]
            if c[3]:
                g[y][x] = SYM[c[:3]]
    return g

def render(g):
    im = Image.new('RGBA', (FW, FH), (0, 0, 0, 0))
    px = im.load()
    for y in range(FH):
        for x in range(FW):
            ch = g[y][x]
            if ch != '.':
                px[x, y] = PAL[ch] + (255,)
    return im

# ------------------------------------------------------------ UP: Overlay auf das gespiegelte Original
# Spalten:   012345678901234567890123456789012345   ('.' = gespiegeltes Original behalten)
UP_OVERLAY = layer("""
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
...........EHHHMHJJMNHHE............
............EHHMHJHMNHJE............
............EVHMHJHMNHVE............
............EVHNHJHNJHVE............
..............VHNHJHNHV.............
...............EVEUEVE..............
...............IGGGGI...............
..............BBBBBBBB..............
..............BQQQQSSB..............
..............BIKIIISB..............
..............BIKBBISB..............
...............BIIIIB...............
....................................
""")

def star_pixels(frame_grid, dy):
    """Sternpixel eines Original-Frames, relativ zur Sternmitte (ohne Bob)."""
    pts = []
    for y in range(FH):
        for x in range(FW):
            ch = frame_grid[y][x]
            if ch in 'XU' and x >= 20 and y <= 17:
                pts.append((x - STAR_CENTER[0], y - dy - STAR_CENTER[1], ch))
    return pts

def build_up(frame_grid, f):
    g = mirror(frame_grid)
    dy = DY[f]
    # Sternpixel liegen im gespiegelten Bild links vom Kopf; nicht übermalen
    stars = {(35 - x - 0, y) for y in range(FH) for x in range(FW)
             if frame_grid[y][x] in 'XU' and x >= 20 and y <= 17}
    blit(g, UP_OVERLAY, 0, dy, skip=lambda x, y: (x, y) in stars)
    return g

# ------------------------------------------------------------ RIGHT: Ebenen (Blick nach rechts)
# Spalten:   012345678901234567890123456789012345
R_HEAD = layer("""
....................................
....................................
....................................
....................................
....................................
.................E..................
................EME.................
.............EEENJEEEE..............
............EJJHNNJEmEE.............
...........EJMHJNHJEnEJE............
...........EVMHJNHMHEHENE...........
...........EJNJNHJHMHJHNE...........
...........EHHNMHJHMHJWHE...........
...........EVJHNHJHWWgWZO...........
...........EVJHNHJHWWklZfO..........
...........EVJHHJHHWZijZO...........
............EVHJHMdWZZfO............
.............EHEUWWWWO..............
.................OUUO...............
""")

R_TORSO = layer("""
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
..............BBBBBBBB..............
..............BIIKKYPB..............
..............BIIKKYPB..............
..............BIIKKYPB..............
..............BIIKKYPB..............
..............BIIKKYPB..............
..............BGIIKGaB..............
...................aPB..............
""")

R_ARM = layer("""
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
.................GIK................
.................GIK................
.................GIK................
.................GIK................
.................GIK................
.................OeO................
..................O.................
""")

R_LEG_NEAR = layer("""
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
...............LRRTL................
...............LRRTL................
...............LTTRL................
................LLLL................
................BhTBB...............
................BbbBB...............
.................BBB................
""")

R_LEG_FAR = layer("""
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
..............LLRRL.................
..............LLRRL.................
..............LLTRL.................
...............LLLL.................
...............BhTBB................
...............BbbBB................
................BBB.................
""")

R_THRUSTER = layer("""
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
........BBBBBBB.....................
........BQQQSSB.....................
........BBBBBSB.....................
.............SB.....................
.............B......................
""")

# LEFT: erhobener Arm (ihre linke Faust wie im Original), liegt über dem Kopf
L_ARM = layer("""
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
....................................
.................OOO................
.................OeO................
.................KIG................
.................KIG................
.................KIG................
.................KIG................
.................KIG................
.................KIG................
""")

L_HEAD, L_TORSO, L_LEG_NEAR, L_LEG_FAR, L_THRUSTER = (
    mirror(R_HEAD), mirror(R_TORSO), mirror(R_LEG_NEAR), mirror(R_LEG_FAR), mirror(R_THRUSTER))
LEFT_STAR_CENTER = (16, 12)

def copy_flame(dst, frame_grid, x0, x1, dx):
    for y in range(FH):
        for x in range(x0, x1 + 1):
            ch = frame_grid[y][x]
            if ch != '.' and PAL[ch] in FLAME and 0 <= x + dx < FW:
                dst[y][x + dx] = ch

def build_side(frame_grid, f, facing):
    g = new_grid()
    dy = DY[f]
    if facing == 'right':
        copy_flame(g, frame_grid, 3, 12, +4)            # linke Original-Flamme unter die Düse
        blit(g, R_THRUSTER, 0, dy)
        far_dx = 1 if f in LEFT_LEG_KICK else 0         # fernes Bein = ihr linkes
        near_dx = 1 if f in RIGHT_LEG_KICK else 0       # nahes Bein = ihr rechtes
        blit(g, R_LEG_FAR, far_dx, dy)
        blit(g, R_TORSO, 0, dy)
        blit(g, R_LEG_NEAR, near_dx, dy)
        blit(g, R_ARM, 0, dy)
        blit(g, R_HEAD, 0, dy)
    else:
        copy_flame(g, frame_grid, 23, 32, -4)           # rechte Original-Flamme
        blit(g, L_THRUSTER, 0, dy)
        far_dx = -1 if f in RIGHT_LEG_KICK else 0       # fernes Bein = ihr rechtes
        near_dx = -1 if f in LEFT_LEG_KICK else 0       # nahes Bein = ihr linkes
        blit(g, L_LEG_FAR, far_dx, dy)
        blit(g, L_TORSO, 0, dy)
        blit(g, L_LEG_NEAR, near_dx, dy)
        blit(g, L_HEAD, 0, dy)
        blit(g, L_ARM, 0, dy)
        for rx, ry, ch in star_pixels(frame_grid, dy):
            x, y = LEFT_STAR_CENTER[0] + rx, LEFT_STAR_CENTER[1] + ry + dy
            if 0 <= x < FW and 0 <= y < FH:
                g[y][x] = ch
    return g

ORDER = ['up', 'right', 'down', 'left']

def build_sheet():
    src = Image.open(SRC).convert('RGBA')
    frames = [src.crop((i * FW, 0, (i + 1) * FW, FH)) for i in range(NF)]
    grids = [grid_from_image(fr) for fr in frames]
    sheet = Image.new('RGBA', (FW * NF, FH * 4), (0, 0, 0, 0))
    rows = {}
    for r, d in enumerate(ORDER):
        rows[d] = []
        for f in range(NF):
            if d == 'down':
                im = frames[f]
            elif d == 'up':
                im = render(build_up(grids[f], f))
            else:
                im = render(build_side(grids[f], f, d))
            rows[d].append(im)
            sheet.paste(im, (f * FW, r * FH))
    return sheet, rows

def main():
    preview_dir = None
    if '--preview' in sys.argv:
        preview_dir = sys.argv[sys.argv.index('--preview') + 1]
    os.makedirs(OUT_DIR, exist_ok=True)
    sheet, rows = build_sheet()
    sheet.save(os.path.join(OUT_DIR, 'cool-rescuer-monia.png'))
    if preview_dir:
        os.makedirs(preview_dir, exist_ok=True)
        S = 8
        GREEN = (32, 156, 0, 255)
        # Frame 0 aller Richtungen nebeneinander
        big = Image.new('RGBA', (4 * (FW * S + S) + S, FH * S + 2 * S), GREEN)
        for i, d in enumerate(ORDER):
            im = rows[d][0].resize((FW * S, FH * S), Image.NEAREST)
            big.paste(im, (S + i * (FW * S + S), S), im)
        big.save(os.path.join(preview_dir, 'monia_dirs_x8.png'))
        # GIF über alle 32 Frames
        gif = []
        for f in range(NF):
            fr = Image.new('RGBA', (4 * (FW * 5 + 5) + 5, FH * 5 + 10), GREEN)
            for i, d in enumerate(ORDER):
                im = rows[d][f].resize((FW * 5, FH * 5), Image.NEAREST)
                fr.paste(im, (5 + i * (FW * 5 + 5), 5), im)
            gif.append(fr.convert('P', palette=Image.ADAPTIVE))
        gif[0].save(os.path.join(preview_dir, 'monia_dirs.gif'), save_all=True,
                    append_images=gif[1:], duration=70, loop=0, disposal=2)
    print('ok', sheet.size)

if __name__ == '__main__':
    main()
